language: node_js
node_js:
  - "8"

cache:
  directories:
  - node_modules
notifications:
  email:
    - sway.liang@gmail.com
script: 
  - cd packages/webpack/vanilla/demo/
  - npm install
  - npm run build